/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FrameComponent1WhereInput } from "./FrameComponent1WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class FrameComponent1CountArgs {
  @ApiProperty({
    required: false,
    type: () => FrameComponent1WhereInput,
  })
  @Field(() => FrameComponent1WhereInput, { nullable: true })
  @Type(() => FrameComponent1WhereInput)
  where?: FrameComponent1WhereInput;
}

export { FrameComponent1CountArgs as FrameComponent1CountArgs };
