/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FrameComponent2WhereUniqueInput } from "./FrameComponent2WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class DeleteFrameComponent2Args {
  @ApiProperty({
    required: true,
    type: () => FrameComponent2WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FrameComponent2WhereUniqueInput)
  @Field(() => FrameComponent2WhereUniqueInput, { nullable: false })
  where!: FrameComponent2WhereUniqueInput;
}

export { DeleteFrameComponent2Args as DeleteFrameComponent2Args };
