/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FrameComponent2WhereInput } from "./FrameComponent2WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class FrameComponent2ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => FrameComponent2WhereInput,
  })
  @ValidateNested()
  @Type(() => FrameComponent2WhereInput)
  @IsOptional()
  @Field(() => FrameComponent2WhereInput, {
    nullable: true,
  })
  every?: FrameComponent2WhereInput;

  @ApiProperty({
    required: false,
    type: () => FrameComponent2WhereInput,
  })
  @ValidateNested()
  @Type(() => FrameComponent2WhereInput)
  @IsOptional()
  @Field(() => FrameComponent2WhereInput, {
    nullable: true,
  })
  some?: FrameComponent2WhereInput;

  @ApiProperty({
    required: false,
    type: () => FrameComponent2WhereInput,
  })
  @ValidateNested()
  @Type(() => FrameComponent2WhereInput)
  @IsOptional()
  @Field(() => FrameComponent2WhereInput, {
    nullable: true,
  })
  none?: FrameComponent2WhereInput;
}
export { FrameComponent2ListRelationFilter as FrameComponent2ListRelationFilter };
