/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FrameComponent2Service } from "../frameComponent2.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FrameComponent2CreateInput } from "./FrameComponent2CreateInput";
import { FrameComponent2 } from "./FrameComponent2";
import { FrameComponent2FindManyArgs } from "./FrameComponent2FindManyArgs";
import { FrameComponent2WhereUniqueInput } from "./FrameComponent2WhereUniqueInput";
import { FrameComponent2UpdateInput } from "./FrameComponent2UpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FrameComponent2ControllerBase {
  constructor(
    protected readonly service: FrameComponent2Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FrameComponent2 })
  @nestAccessControl.UseRoles({
    resource: "FrameComponent2",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFrameComponent2(
    @common.Body() data: FrameComponent2CreateInput
  ): Promise<FrameComponent2> {
    return await this.service.createFrameComponent2({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FrameComponent2] })
  @ApiNestedQuery(FrameComponent2FindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FrameComponent2",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async frameComponent2s(
    @common.Req() request: Request
  ): Promise<FrameComponent2[]> {
    const args = plainToClass(FrameComponent2FindManyArgs, request.query);
    return this.service.frameComponent2s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FrameComponent2 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FrameComponent2",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async frameComponent2(
    @common.Param() params: FrameComponent2WhereUniqueInput
  ): Promise<FrameComponent2 | null> {
    const result = await this.service.frameComponent2({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FrameComponent2 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FrameComponent2",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFrameComponent2(
    @common.Param() params: FrameComponent2WhereUniqueInput,
    @common.Body() data: FrameComponent2UpdateInput
  ): Promise<FrameComponent2 | null> {
    try {
      return await this.service.updateFrameComponent2({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FrameComponent2 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FrameComponent2",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFrameComponent2(
    @common.Param() params: FrameComponent2WhereUniqueInput
  ): Promise<FrameComponent2 | null> {
    try {
      return await this.service.deleteFrameComponent2({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
