/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FrameComponent2WhereInput } from "./FrameComponent2WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class FrameComponent2CountArgs {
  @ApiProperty({
    required: false,
    type: () => FrameComponent2WhereInput,
  })
  @Field(() => FrameComponent2WhereInput, { nullable: true })
  @Type(() => FrameComponent2WhereInput)
  where?: FrameComponent2WhereInput;
}

export { FrameComponent2CountArgs as FrameComponent2CountArgs };
